config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :blogs do
    collection do
      get :top_search
      post :upload_image
      get :add_comments
    end
  end

  namespace :admin do

  resources :categories do
      collection do
        get :show_name
      end  
  end

  resources :comments do
      collection do
        get :show_name
      end  
  end  
  resources :permissions do
      collection do
        get :show_name
        get  :add_roles
        post :save_roles
      end  
    end

    
  resources :roles do
      collection do
        get  :add_permissions
        post :save_permissions
	get  :add_employees
	post :save_employees
      end  
  end  



    resources :employees do
      collection do
        get  :forget_password
        post :forget_password
        get  :reset_mail
        get  :error_mail
        get  :add_roles
        post :save_roles
        get  :desboart
      end
    end
    resources :blogs do
      collection do
        post :upload_image
      end
    end

    resources :categories do
    end
   
  end

  devise_for :employees, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' }, controllers: { sessions: "admin/sessions", passwords: "admin/passwords"}
  root to: 'blogs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :blog
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController
	before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
   # @comments = Comment.all
    @q = SearchParams.new(params[:search_params] || {})
    @comments = Comment.default_where(@q.attributes(self)).page(params[:page]).per(10)
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end
  

  def show_name
    @comment = Comment.find(params[:id])
    render json: {name: @comment.content}
  end
  

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.save
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
     @comment.update(comment_params)
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:blog_id,:content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_edit.html.erb

<%= simple_form_for @comment, url: admin_comment_path(@comment) , method: :put, remote: true, html: {id:"edit_point_vendor"} do |f| %>
  
    <div id="form_message" class="two fields red" style="margin-left: 15px;display:none;" ></div>

    <div class="two fields">
      <%= f.input :content %>
    </div>
    <div class="two fields">
      <%= f.input :blog_id %>
    </div>

    <div class="field">
      <div class="actions ">
        <div class="ui button primary" id="commition" >提交</div>
        <div class="ui cancel button">取消</div>
      </div>
    </div>

<% end %>





app/views/admin/comments/_list.html.erb
<tr id="comment_<%= comment.id %>" >
  <td class="top aligned">
    <%= comment.content %>
  </td>
  <td class="top aligned">
   <%= comment.blog_id %>
  </td>
  
  <td class="center aligned">
    <%= link_to edit_admin_comment_path(comment.id) , remote: true, class: 'ui icon primary button', 'data-content' => '修改评论', 'data-variation' => 'inverted'  do%>
      <i class="edit icon"></i>
    <% end %>
  </td>  
</tr>

app/views/admin/comments/_new.html.erb
<%= simple_form_for @comment, url: admin_comments_path , method: :post, remote: true do |f| %>
  
    <div id="form_message" class="two fields red" style="margin-left: 15px;display:none;" ></div>

    <div class="two fields">
      <%= f.input :content %>
    </div>
    <div class="two fields">
      <%= f.input :blog_id %><span id="show_name"></span>
    </div>

    <div class="field">
      <div class="actions ">
        <div class="ui button primary" id="commition" >提交</div>
        <div class="ui cancel button">取消</div>
      </div>
    </div>

<% end %>

app/views/admin/comments/_search_form.html.erb
<div class = "ui blue segent">
	<%= simple_form_for @q,  url: admin_comments_path, method: :get, wrapper: 'semantic_search_form' do |f| %>
	<div class="ui five column grid">
		<%= f.input "blog_id-like", placeholder: 'blog_id' %>
		<div class="column">
			<%= f.submit '搜索', class: 'ui primary button' %>
		</div>
	</div>
	<% end %>
</div>

app/views/admin/comments/create.js.erb
<% if @comment.errors.blank? %>
  $("tbody").prepend('<%= j render('list', comment: @comment) %>');
  $("#comment_modal").modal('hide');
<% else %>
  $(".field .red.pointing").remove();
  <% @comment.errors.messages.each do |key, value| %>
    $("#comment_<%= key %>").parent().addClass('error');
    $("#comment_<%= key %>").parent().append("<div class='ui basic red pointing prompt label transition visible'><%= value[0] %></div>");
  <% end %>
<% end %>

$(".button").popup();
$(".icon").popup();
$(document).find('.dropdown').dropdown({
    on: 'hover'
});

app/views/admin/comments/edit.js.erb
$('#comment_modal').remove();
$('body').append('<div class="ui modal" id="comment_modal"><i class="close icon"></i><h2 class="ui dividing header">修改评论</h2><%= j(render 'edit') %></div>');
$('#comment_modal').modal('setting', {autofocus: false}).modal('show');
$('select.dropdown').dropdown();

// TODO表单校验
  $("#commition").click(function(){
    if( $("#comment").val() !="" ){
      $("#edit_point_vendor").submit(); 
    }else{
      $("#form_message").text("请完善信息！").show(200);
    }
  });
  

app/views/admin/comments/index.html.erb
<div class="ui grid">
  <div class="left floated fourteen wide column">
    <h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a>评论管理</h2>
  </div>
</div>
 
  <%= render :partial => "search_form" %>


<div class="ui blue segment">
  <div class="ui grid">
     <div class="left floated wide column">
	<%= link_to '新增评论', new_admin_comment_path, class: 'ui primary   button', remote: true  %>
     </div>
  </div>

 
  <table class="ui selectable striped celled table">
     <thead>
       <tr>
         <th class="center aligned">CONTENT</th>
         <th class="center aligned">Blog_ID</th>
         <th class="center aligned">操作</th>
       </tr>
     </thead>
  <tbody>
    <%= render :partial => "list", :collection => @comments, :as => :comment %>
  </tbody>
  </table>

  <span class="blue">
      <%= page_entries_info(@comments) %>
   </span>
   <%= paginate(@comments, :theme => 'admin')%>
  
  

</div>

app/views/admin/comments/new.js.erb
$('#comment_modal').remove();
$('body').append('<div class="ui modal" id="comment_modal"><i class="close icon"></i><h2 class="ui dividing header">添加评论</h2><%= j(render 'new') %></div>');
$('#comment_modal').modal('setting', {autofocus: false}).modal('show');
$('select.dropdown').dropdown();

// TODO表单校验
  $("#commition").click(function(){
    if( $("#comment_content").val() !="" ){
      $("#new_comment").submit(); 
    }else{
      $("#form_message").text("请完善信息！").show(200);
    }
  });

$('#comment_blog_id').change(function(){
  	  var parent_id = $('#comment_blog_id').val()
  	  if (blog_id != ""){
	  	  $.ajax({
	          url: "/admin/comments/show_name",
	          type: "get",
	          data: {id: blog_id},
	          success: function(data){
	            $("#show_name").html(data.name )
	          }
	        });
	      }
    })

app/views/admin/comments/update.js.erb
<% if @comment.errors.blank? %>
  $("#comment_<%= @comment.id %>").replaceWith("<%= j(render partial: 'list', locals: { comment: @comment} ) %>");
  $("#comment_modal").modal('hide');
<% else %>
  $(".field .red.pointing").remove();
  <% @comment.errors.messages.each do |key, value| %>
    $("#comment_<%= key %>").parent().addClass('error');
    $("#comment_<%= key %>").parent().append("<div class='ui basic red pointing prompt label transition visible'><%= value[0] %></div>");
  <% end %>
<% end %>

$(".button").popup();
$(".icon").popup();
$(document).find('.dropdown').dropdown({
    on: 'hover'
});