config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :blogs do
    collection do
      get :top_search
      post :upload_image
      get :add_comments
    end
  end

  namespace :admin do

  resources :categories do
      collection do
        get :show_name
      end  
  end

  resources :comments do
      collection do
        get :show_name
      end  
  end  
  resources :permissions do
      collection do
        get :show_name
        get  :add_roles
        post :save_roles
      end  
    end

    
  resources :roles do
      collection do
        get  :add_permissions
        post :save_permissions
	get  :add_employees
	post :save_employees
      end  
  end  



    resources :employees do
      collection do
        get  :forget_password
        post :forget_password
        get  :reset_mail
        get  :error_mail
        get  :add_roles
        post :save_roles
        get  :desboart
      end
    end
    resources :blogs do
      collection do
        post :upload_image
      end
    end

    resources :categories do
    end
   
  end

  devise_for :employees, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' }, controllers: { sessions: "admin/sessions", passwords: "admin/passwords"}
  root to: 'blogs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/role.rb
class Role < ApplicationRecord

has_and_belongs_to_many :employees
has_and_belongs_to_many :permissions


end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::BaseController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @q = SearchParams.new(params[:search_params] || {})
    @roles = Role.default_where(@q.attributes(self)).page(params[:page]).per(10)
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  def show_name
    @role = Role.find(params[:id])
    render json: {name: @role.name}
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)
    @role.save
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json

  def add_permissions
    @role = Role.find(params[:id])
  end

  def save_permissions
    @role = Role.find(params[:id])
    @role.permission_ids = params[:role][:permission_ids]
  end
	
  def add_employees
    @role = Role.find(params[:id])
  end

  def save_employees
    @role = Role.find(params[:id])
    @role.employee_ids = params[:role][:employee_ids]
  end

  def update
    @role.update(role_params)
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to "index", notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:parent_id,:name)
    end
end

app/views/admin/roles/_add_employees.html.erb
<%= simple_form_for @role, url: save_employees_admin_roles_path(id:@role.id) , method: :post, remote: true, html: {id:"add_employees"} do |f| %>
  
    <div id="form_message" class="two fields red" style="margin-left: 15px;display:none;" ></div>

    <% Employee.all.each do |employee|%>
	    <label class="checkbox">
	      <%= check_box_tag "role[employee_ids][]",employee.id,@role.employee_ids.include?(employee.id)%> <%= employee.name %>
	    </label>
	<% end %>
	<br/>
    
    <div class="field">
      <div class="actions ">
        <div class="ui button primary" id="commition" >提交</div>
        <div class="ui cancel button">取消</div>
      </div>
    </div>

<% end %>

app/views/admin/roles/_add_permissions.html.erb
<%= simple_form_for @role, url: save_permissions_admin_roles_path(id:@role.id) , method: :post, remote: true, html: {id:"add_permissions"} do |f| %>
  
    <div id="form_message" class="two fields red" style="margin-left: 15px;display:none;" ></div>

    <% Permission.all.each do |permission|%>
	    <label class="checkbox">
	      <%= check_box_tag "role[permission_ids][]",permission.id,@role.permission_ids.include?(permission.id)%> <%= permission.name %>
	    </label>
	<% end %>
	<br/>
    
    <div class="field">
      <div class="actions ">
        <div class="ui button primary" id="commition" >提交</div>
        <div class="ui cancel button">取消</div>
      </div>
    </div>

<% end %>

app/views/admin/roles/_list.html.erb
<tr id="role_<%= role.id %>" >
  <td class="top aligned">
    <%= role.id %>
  </td>
  <td class="top aligned">
   <%= role.name %>
  </td>
  <td class="center aligned">
  <%= link_to add_permissions_admin_roles_path(id:role.id), remote: true, data: {content: '分配权限', variation: 'inverted'}, class: 'ui green icon button' do %>
  <i class="hand pointer icon"></i>
  <% end %>

  <%= link_to add_employees_admin_roles_path(id:role.id), remote: true, data: {content: '员工配置', variation: 'inverted'}, class: 'ui blue icon button' do %>
  <i class="hand pointer icon"></i>
  <% end %>
  </td>
</tr>

app/views/admin/roles/add_employees.js.erb
$('#addemployee_modal').remove();
$('body').append('<div class="ui modal" id="addemployee_modal"><i class="close icon"></i><h2 class="ui dividing header">员工配置</h2><%= j(render 'add_employees') %></div>');
$('#addemployee_modal').modal('setting', {autofocus: false}).modal('show');
$('select.dropdown').dropdown();

$("#commition").click(function(){
    $("#add_employees").submit(); 
});

app/views/admin/roles/add_permissions.js.erb
$('#addpermission_modal').remove();
$('body').append('<div class="ui modal" id="addpermission_modal"><i class="close icon"></i><h2 class="ui dividing header">分配权限</h2><%= j(render 'add_permissions') %></div>');
$('#addpermission_modal').modal('setting', {autofocus: false}).modal('show');
$('select.dropdown').dropdown();

$("#commition").click(function(){
    $("#add_permissions").submit(); 
});

app/views/admin/roles/index.html.erb
<div class="ui grid">
  <div class="left floated fourteen wide column">
    <h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a>角色管理</h2>
  </div>
</div>
 
  


<div class="ui blue segment">
  
  <table class="ui selectable striped celled table">
     <thead>
       <tr>
         <th class="center aligned">ID</th>
         <th class="center aligned">NAME</th>
         <th class="center aligned">操作</th>
       </tr>
     </thead>
  <tbody>
    <%= render :partial => "list", :collection => @roles, :as => :role %>
  </tbody>
  </table>

  <span class="blue">
      <%= page_entries_info(@roles) %>
   </span>
   <%= paginate(@roles, :theme => 'admin')%>
  
  

</div>

app/views/admin/roles/save_employees.js.erb
 $("#addemployee_modal").modal('hide');

app/views/admin/roles/save_permissions.js.erb
 $("#addpermission_modal").modal('hide');