config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :blogs do
    collection do
      get :top_search
      post :upload_image
      get :add_comments
    end
  end

  namespace :admin do

  resources :categories do
      collection do
        get :show_name
      end  
  end

  resources :comments do
      collection do
        get :show_name
      end  
  end  
  resources :permissions do
      collection do
        get :show_name
        get  :add_roles
        post :save_roles
      end  
    end

    
  resources :roles do
      collection do
        get  :add_permissions
        post :save_permissions
	get  :add_employees
	post :save_employees
      end  
  end  



    resources :employees do
      collection do
        get  :forget_password
        post :forget_password
        get  :reset_mail
        get  :error_mail
        get  :add_roles
        post :save_roles
        get  :desboart
      end
    end
    resources :blogs do
      collection do
        post :upload_image
      end
    end

    resources :categories do
    end
   
  end

  devise_for :employees, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' }, controllers: { sessions: "admin/sessions", passwords: "admin/passwords"}
  root to: 'blogs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
has_many :blogs
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @q = SearchParams.new(params[:search_params] || {})
    @categories = Category.default_where(@q.attributes(self)).page(params[:page]).per(10)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  def show_name
    @category = Category.find(params[:id])
    render json: {name: @category.name}
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    @category.save
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    @category.update(category_params)
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to "index", notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:parent_id,:name)
    end
end

app/views/admin/categories/_edit.html.erb
<%= simple_form_for @category, url: admin_category_path(@category) , method: :put, remote: true, html: {id:"edit_point_vendor"} do |f| %>
  
    <div id="form_message" class="two fields red" style="margin-left: 15px;display:none;" ></div>

    <div class="two fields">
      <%= f.input :name %>
      <%= f.input :parent_id %>
    </div>

    <div class="field">
      <div class="actions ">
        <div class="ui button primary" id="commition" >提交</div>
        <div class="ui cancel button">取消</div>
      </div>
    </div>

<% end %>

app/views/admin/categories/_list.html.erb
<tr id="category_<%= category.id %>" >
  <td class="top aligned">
    <%= category.name %>
  </td>
  <td class="top aligned">
   <%= category.parent_id %>
  </td>
  <td class="center aligned">
    <%= link_to edit_admin_category_path(category.id) , remote: true, class: 'ui icon primary button', 'data-content' => '修改分类', 'data-variation' => 'inverted'  do%>
      <i class="edit icon"></i>
    <% end %>
  </td>  
</tr>

app/views/admin/categories/_new.html.erb
<%= simple_form_for @category, url: admin_categories_path , method: :post, remote: true do |f| %>
  
    <div id="form_message" class="two fields red" style="margin-left: 15px;display:none;" ></div>

    <div class="two fields">
      <%= f.input :name %>
      <%= f.input :parent_id %><span id="show_name"></span>
    </div>

    <div class="field">
      <div class="actions ">
        <div class="ui button primary" id="commition" >提交</div>
        <div class="ui cancel button">取消</div>
      </div>
    </div>

<% end %>

app/views/admin/categories/_search_form.html.erb
<div class="ui blue segment">
  <%= simple_form_for @q,  url: admin_categories_path, method: :get, wrapper: 'semantic_search_form' do |f| %>
    <div class="ui five column grid">
      <%= f.input "name-like", placeholder: '名称' %>
      <div class="column">
        <%= f.submit '搜索', class: 'ui primary button' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/categories/create.js.erb
<% if @category.errors.blank? %>
  $("tbody").prepend('<%= j render('list', category: @category) %>');
  $("#category_modal").modal('hide');
<% else %>
  $(".field .red.pointing").remove();
  <% @category.errors.messages.each do |key, value| %>
    $("#category_<%= key %>").parent().addClass('error');
    $("#category_<%= key %>").parent().append("<div class='ui basic red pointing prompt label transition visible'><%= value[0] %></div>");
  <% end %>
<% end %>

$(".button").popup();
$(".icon").popup();
$(document).find('.dropdown').dropdown({
    on: 'hover'
});

app/views/admin/categories/edit.js.erb
$('#category_modal').remove();
$('body').append('<div class="ui modal" id="category_modal"><i class="close icon"></i><h2 class="ui dividing header">修改类型</h2><%= j(render 'edit') %></div>');
$('#category_modal').modal('setting', {autofocus: false}).modal('show');
$('select.dropdown').dropdown();

// TODO表单校验
  $("#commition").click(function(){
    if( $("#category_name").val() !="" ){
      $("#edit_point_vendor").submit(); 
    }else{
      $("#form_message").text("请完善信息！").show(200);
    }
  });
  

app/views/admin/categories/index.html.erb
<div class="ui grid">
  <div class="left floated fourteen wide column">
    <h2><a href="javascript:history.back()"><i class="blue reply icon"></i></a>分类管理</h2>
    <h2><%= controller_name %>分类管理 <%= action_name %> </h2>
  </div>
</div>

 <%= render :partial => "search_form" %>

  <div class="ui blue segment">
    <div class="ui grid">
    <div class="left floated wide column">
      <%= link_to '新增分类', new_admin_category_path, class: 'ui primary button', remote: true  %>
    </div>
  </div>
    <table class="ui selectable striped celled table">
      <thead>
        <tr>
          <th class="center aligned">名称</th>
          <th class="center aligned">父ID</th>
          <th class="center aligned">操作</th>
        </tr>
      </thead>
      <tbody>
        <%= render :partial => "list", :collection => @categories, :as => :category %>
      </tbody>
    </table>
    <span class="blue">
      <%= page_entries_info(@categories) %>
    </span>
    <%= paginate(@categories, :theme => 'admin')%>
  </div>

app/views/admin/categories/new.js.erb
$('#category_modal').remove();
$('body').append('<div class="ui modal" id="category_modal"><i class="close icon"></i><h2 class="ui dividing header">添加类型</h2><%= j(render 'new') %></div>');
$('#category_modal').modal('setting', {autofocus: false}).modal('show');
$('select.dropdown').dropdown();

// TODO表单校验
  $("#commition").click(function(){
    if( $("#category_name").val() !="" ){
      $("#new_category").submit(); 
    }else{
      $("#form_message").text("请完善信息！").show(200);
    }
  });

$('#category_parent_id').change(function(){
  	  var parent_id = $('#category_parent_id').val()
  	  if (parent_id != ""){
	  	  $.ajax({
	          url: "/admin/categories/show_name",
	          type: "get",
	          data: {id: parent_id},
	          success: function(data){
	            $("#show_name").html(data.name 

)
	          }
	        });
	      }
    })

  

app/views/admin/categories/update.js.erb
<% if @category.errors.blank? %>
  $("#category_<%= @category.id %>").replaceWith("<%= j(render partial: 'list', locals: { category: @category} ) %>");
  $("#category_modal").modal('hide');
<% else %>
  $(".field .red.pointing").remove();
  <% @category.errors.messages.each do |key, value| %>
    $("#category_<%= key %>").parent().addClass('error');
    $("#category_<%= key %>").parent().append("<div class='ui basic red pointing prompt label transition visible'><%= value[0] %></div>");
  <% end %>
<% end %>

$(".button").popup();
$(".icon").popup();
$(document).find('.dropdown').dropdown({
    on: 'hover'
});