config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :blogs do
    collection do
      get :top_search
      post :upload_image
      get :add_comments
    end
  end

  namespace :admin do

  resources :categories do
      collection do
        get :show_name
      end  
  end

  resources :comments do
      collection do
        get :show_name
      end  
  end  
  resources :permissions do
      collection do
        get :show_name
        get  :add_roles
        post :save_roles
      end  
    end

    
  resources :roles do
      collection do
        get  :add_permissions
        post :save_permissions
	get  :add_employees
	post :save_employees
      end  
  end  



    resources :employees do
      collection do
        get  :forget_password
        post :forget_password
        get  :reset_mail
        get  :error_mail
        get  :add_roles
        post :save_roles
        get  :desboart
      end
    end
    resources :blogs do
      collection do
        post :upload_image
      end
    end

    resources :categories do
    end
   
  end

  devise_for :employees, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' }, controllers: { sessions: "admin/sessions", passwords: "admin/passwords"}
  root to: 'blogs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/admin/_sidebar.html.erb
<div class="ui vertical fluid menu" id="verticalMenu">
 <ul>
    <li>
      <a class="item">
        <i class="legal icon"></i>
        <span class="main_menu">文章管理</span>
        <i class="right dropdown icon"></i>
      </a>
      <div class="menu content child active">
        <%= link_to admin_blogs_path, class: 'item', active_class: 'actives' do %>
          <i class="left bullseye icon"></i>
          <span>文章管理</span>
        <% end %>
        <%= link_to admin_categories_path, class: 'item', active_class: 'actives' do %>
          <i class="left bullseye icon"></i>
          <span>类型管理</span>
        <% end %>
      </div>
    </li>
  <li>
      <a class="item">
        <i class="configure icon"></i>
        <span class="main_menu">系统管理</span>
        <i class="right dropdown icon"></i>
      </a>
      <div class="menu content child active">
        <%= link_to admin_employees_path, class: 'item', active_class: 'actives' do %>
          <i class="left bullseye icon"></i>
          <span>员工管理</span>
        <% end %>
        <%= link_to admin_permissions_path, class: 'item', active_class: 'actives' do %>
          <i class="left bullseye icon"></i>
          <span>权限管理</span>
        <% end %>
        <%= link_to admin_roles_path, class: 'item', active_class: 'actives' do %>
          <i class="left bullseye icon"></i>
          <span>角色管理</span>
        <% end %>
      </div>
    </li>

  </ul>


</div>

app/views/shared/admin/_top_bar.html.erb
<div class="ui fixed top menu">
  <a href="javascript:void(0)" class="icon active item" id="hideToggle" style="display: flex;"><h3><i class="content icon"></i></h3></a>
  <a href="javascript:void(0)" class="icon active item" id="showToggle" style="display: none;"><h3><i class="content icon"></i></h3></a>
  <a href="#" data-toggle="slide" class="item"><h3>Schooltop</h3></a>
  <div class="menu right">
    <a class="icon item pointer" data-toggle="popup" data-content="#mail" data-position="bottom right"><i class="mail icon"></i></a>
    <a class="icon item pointer" data-toggle="popup" data-content="#notif" data-position="bottom right"><i class="bell icon"></i></a>
    <!-- 头像 -->
    <div class="item"><span><%= current_employee.name %></span></div>
    <a class="icon item pointer" data-toggle="popup" data-content="#user" data-position="bottom right">
      <%= image_tag 'male.jpg', class: 'ui avatar image' %>
    </a>
    <div id="user" class="ui popup">
      <div class="ui secondary vertical menu">
        <div class="header item">USER MENU</div>
          <%= link_to  edit_employee_password_path, class: 'item' do %>
            Change Password  <i class="privacy icon"></i>
          <% end %> 
          <%= link_to destroy_employee_session_path,method: 'delete', class: 'item' do %>
            Logout <i class="sign out icon"></i>
          <% end %>
      </div>
    </div>
  </div>
</div>